language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: o4Ego9do46Byd3i2AisnSkdXRdBAZxsmGqOB3pa+bmndHsp4j2wol7QoaMOGeQwcwbpvKtcjDYJFBaClzuCVCSxJD1YtkJMuqT0kpREvd1Qzn3S6Yjth0kcUceC9zjRKFaHNIsfbpC4GawdXvEITDjGaEY1yu7/J8asr+2Rd4adnmuY5ef2mgAUUIgl2iKQEfdc4kGxnfYIEnR9NYhPMyySjAK0x8MHWzPELonEaJqJ/P3R41Mdr6FkZYzDNeRIkVUKeLVaGmOkHn8ToqfyhxK/gW2kHzPOeaQTT8DgOOludZXAm605+Stza3n5tf1SGERRGN13UtFJBm1TS4efXLef0LxBdX4r3YG0GY2JFWhrR/uu6i0xXpdufyqwBnmlhdwI6yj73Jgx1dAQDHR9MIEXmqSCEZx80H0xWk21b/kQPnrjbVUBjoJCmr2pgkzqLdcYrsWxT2poCGf2HwH71vCUsAUnB0GssFIjcayJ7Q+/0tvrrfrAHiMfKKJfm/nE1Y7EyzYgq1KweXyzgjBOo86BLvZMToSpHPCOIE4IcZzezaOVC3HtL10ZgZmcp1UzYXnbvvfNZqFbCedr2jdNepmkjgv9nEWFfcb3gWp8Z/zcvAu7Hd8N+kaX/OsqBnZcuMSMj6efaZiXekspQJ2hi25SmXvu2fyZnQbJMsXqc3bE=
  app: react-trello-testing
  on:
    repo: oscaralexander2125/react-trello-testing
